version: '3.8'
services:
  api:
    build: ./
    container_name: api
    ports: 
      - "8080:8080"
    depends_on:
      - db
  db:
    build: ./db
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=booking
    volumes:
      - ./data:/data
